SELECT COLUMN_NAME, 
       DATA_TYPE, 
       IS_NULLABLE, 
       COLUMN_DEFAULT, 
       CHARACTER_MAXIMUM_LENGTH, 
       NUMERIC_PRECISION, 
       NUMERIC_SCALE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()  -- Use the database passed as an argument
  AND TABLE_NAME = 'books';